### ISSUE TITLE
Does EMF compare have an API?

### ISSUE THREAD

**Issue by pjljvandelaar** [eclipse-emf-compare/emf-compare#13]
Dear EMF Compare developers,

In my test cases I need to ensure that the expected and actual model represent the same model.
Hence, the models must contain the same nodes and edges, yet the actual values of xmi:id can be ignored.
Hence, I cannot use the textual representation of the expected and actual model, 
since they will differ at the location where xmi:id is defined or used as a reference.
Since I don't want to reinvent the wheel, I would like to reuse the compare functionality of EMF compare in my test cases.
However, I cannot find any documentation related to the API of EMP compare.
Could you point me to this documentation?
And when it doesn't exist yet, can you develop it?

Thanks in advance,

Pierre

P.S. Am I correct to assume that EMF Compare is insensitive to the actual chosen value for xmi:id?

**Comment by Kellindil** [comment]
Hello Pierre,

The actual textual representation doesn't matter much as EMF Compare will use the loaded, in memory models for the comparison.
It does, however, depend on the value of the xmi:id by default.

You can take a look at the [developer guide](https://eclipse.dev/emf/compare/documentation/latest/developer/developer-guide.html) on the EMF Compare website, or directly from the [repository here](https://github.com/eclipse-emf-compare/emf-compare/tree/master/plugins/org.eclipse.emf.compare.doc/src/developer). The section that will make sense for your need is "Configuring the comparison" where an example of how to tell EMF Compare to ignore identifiers is shown.

Regards,
Laurent

**Comment by pjljvandelaar** [comment]
@Kellindil Thanks for the quick answer. I will read through the documents!
Note that I don't want to ignore the identifiers, I just want to ignore their actual values.

Example,
```
<node xmi:id="X" name="dad"/>
<node xmi:id="Y" name="child"/>
<edge xmi:id="Z" name="parent" source="X" target="Y"/>
```
is equivalent with
```
<node xmi:id="1" name="dad"/>
<node xmi:id="2" name="child"/>
<edge xmi:id="3" name="parent" source="1" target="2"/>
```
yet not with 
```
<node xmi:id="1" name="dad"/>
<node xmi:id="2" name="child"/>
<edge xmi:id="3" name="parent" source="2" target="1"/>
```

**Comment by pjljvandelaar** [comment]
Solved it in another way using resources. And setting useUUIDs to false.
