### ISSUE TITLE
Question about EMFComparePredicates deprecated

### ISSUE THREAD

**Issue by Phillipus** [eclipse-emf-compare/emf-compare#19]
(Sorry that this is reported as an issue as this repo does not have the Discussions feature enabled.)

The JavaDoc for [EMFComparePredicates](https://github.com/eclipse-emf-compare/emf-compare/blob/master/plugins/org.eclipse.emf.compare/src/org/eclipse/emf/compare/utils/EMFComparePredicates.java) says:

`@deprecated this class provides Guava predicates. Please consider using EMFCompareJavaPredicates instead.`

I'm using a [BatchMerger](https://github.com/eclipse-emf-compare/emf-compare/blob/master/plugins/org.eclipse.emf.compare/src/org/eclipse/emf/compare/merge/BatchMerger.java) class that only accepts Guava predicates. Is there a way to use this using `EMFCompareJavaPredicates`?

**Comment by Kellindil** [comment]
Hello Phillipus,

This was part of an effort to rid EMF Compare of Guava, but as it was not completed as Guava is too deeply embedded, such as in the APIs as you see there. I can only suggest to suppress or ignore the deprecation warning for this case.

Laurent

**Comment by Phillipus** [comment]
@Kellindil Thank-you for your fast reply. I will take your advice.
